import type { SettlementRecord } from "@/types/settlement";

export const SETTLEMENT_SEED: SettlementRecord[] = [
  {
    id: "st-1",
    event: "India vs Australia",
    market: "Match Winner",
    marketId: "mkt-1001",
    status: "Settled",
    settlementTime: "2026-06-17T12:45:00",
    profitLoss: 4250,
    settledBy: "Priya Sharma",
  },
  {
    id: "st-2",
    event: "CSK vs MI",
    market: "Total Runs Over/Under",
    marketId: "mkt-1006",
    status: "Settled",
    settlementTime: "2026-06-17T11:20:00",
    profitLoss: 1820,
    settledBy: "James Wilson",
  },
  {
    id: "st-3",
    event: "Liverpool vs Arsenal",
    market: "Both Teams to Score",
    marketId: "mkt-1004",
    status: "Pending",
    settlementTime: null,
    profitLoss: null,
    settledBy: null,
  },
  {
    id: "st-4",
    event: "Djokovic vs Alcaraz",
    market: "Set 1 Winner",
    marketId: "mkt-1005",
    status: "Pending",
    settlementTime: null,
    profitLoss: null,
    settledBy: null,
  },
  {
    id: "st-5",
    event: "Barcelona vs Real Madrid",
    market: "Correct Score",
    marketId: "mkt-1007",
    status: "Pending",
    settlementTime: null,
    profitLoss: null,
    settledBy: null,
  },
  {
    id: "st-6",
    event: "Man City vs Tottenham",
    market: "Match Winner",
    marketId: "mkt-1008",
    status: "Failed",
    settlementTime: "2026-06-17T10:30:00",
    profitLoss: null,
    settledBy: null,
  },
  {
    id: "st-7",
    event: "PSG vs Bayern",
    market: "Match Winner",
    marketId: "mkt-0990",
    status: "Settled",
    settlementTime: "2026-06-16T22:15:00",
    profitLoss: 3100,
    settledBy: "Alex Morgan",
  },
  {
    id: "st-8",
    event: "India vs Australia",
    market: "Over/Under",
    marketId: "mkt-1002",
    status: "Pending",
    settlementTime: null,
    profitLoss: null,
    settledBy: null,
  },
];
