import type { SportEvent } from "@/types/event";

export const AVAILABLE_EVENTS_SEED: SportEvent[] = [
  {
    id: "ev-101",
    name: "India vs England",
    sport: "Cricket",
    competition: "Test Series",
    startTime: "2026-06-18T09:30:00",
    status: "Incoming",
    markets: 22,
  },
  {
    id: "ev-102",
    name: "Liverpool vs Chelsea",
    sport: "Football",
    competition: "Premier League",
    startTime: "2026-06-18T14:00:00",
    status: "Incoming",
    markets: 18,
  },
  {
    id: "ev-103",
    name: "Alcaraz vs Djokovic",
    sport: "Tennis",
    competition: "Wimbledon",
    startTime: "2026-06-18T16:00:00",
    status: "Incoming",
    markets: 14,
  },
  {
    id: "ev-104",
    name: "RCB vs KKR",
    sport: "Cricket",
    competition: "IPL",
    startTime: "2026-06-18T19:30:00",
    status: "Incoming",
    markets: 20,
  },
  {
    id: "ev-105",
    name: "Arsenal vs Chelsea",
    sport: "Football",
    competition: "Premier League",
    startTime: "2026-06-19T17:30:00",
    status: "Incoming",
    markets: 16,
  },
  {
    id: "ev-106",
    name: "England vs South Africa",
    sport: "Cricket",
    competition: "ODI Series",
    startTime: "2026-06-19T13:00:00",
    status: "Incoming",
    markets: 18,
  },
  {
    id: "ev-107",
    name: "Nadal vs Djokovic",
    sport: "Tennis",
    competition: "ATP 500",
    startTime: "2026-06-20T18:00:00",
    status: "Incoming",
    markets: 12,
  },
  {
    id: "ev-108",
    name: "Man United vs Newcastle",
    sport: "Football",
    competition: "Premier League",
    startTime: "2026-06-20T20:00:00",
    status: "Incoming",
    markets: 15,
  },
];
