import type { SportEvent } from "@/types/event";

export const LIVE_EVENTS_SEED: SportEvent[] = [
  {
    id: "ev-1",
    name: "India vs Australia",
    sport: "Cricket",
    competition: "Test Series",
    startTime: "2026-06-17T09:30:00",
    status: "Live",
    markets: 24,
    totalBets: 3200,
  },
  {
    id: "ev-2",
    name: "Liverpool vs Arsenal",
    sport: "Football",
    competition: "Premier League",
    startTime: "2026-06-17T14:00:00",
    status: "Live",
    markets: 18,
    totalBets: 2100,
  },
  {
    id: "ev-3",
    name: "Djokovic vs Alcaraz",
    sport: "Tennis",
    competition: "French Open",
    startTime: "2026-06-17T16:30:00",
    status: "Live",
    markets: 12,
    totalBets: 1240,
  },
  {
    id: "ev-4",
    name: "CSK vs MI",
    sport: "Cricket",
    competition: "IPL",
    startTime: "2026-06-17T19:30:00",
    status: "Live",
    markets: 20,
    totalBets: 1850,
  },
  {
    id: "ev-5",
    name: "Barcelona vs Real Madrid",
    sport: "Football",
    competition: "La Liga",
    startTime: "2026-06-17T20:00:00",
    status: "Live",
    markets: 22,
    totalBets: 980,
  },
  {
    id: "ev-6",
    name: "Man City vs Tottenham",
    sport: "Football",
    competition: "Premier League",
    startTime: "2026-06-17T15:00:00",
    status: "Suspended",
    markets: 14,
    totalBets: 640,
  },
];
